export const countryFlags = [
  { name: "Afghanistan", code: "AF", alpha3: "AFG", emoji: "🇦🇫" },
  { name: "Albania", code: "AL", alpha3: "ALB", emoji: "🇦🇱" },
  { name: "Algeria", code: "DZ", alpha3: "DZA", emoji: "🇩🇿" },
  { name: "Andorra", code: "AD", alpha3: "AND", emoji: "🇦🇩" },
  { name: "Angola", code: "AO", alpha3: "AGO", emoji: "🇦🇴" },
  { name: "Antigua and Barbuda", code: "AG", alpha3: "ATG", emoji: "🇦🇬" },
  { name: "Argentina", code: "AR", alpha3: "ARG", emoji: "🇦🇷" },
  { name: "Armenia", code: "AM", alpha3: "ARM", emoji: "🇦🇲" },
  { name: "Australia", code: "AU", alpha3: "AUS", emoji: "🇦🇺" },
  { name: "Austria", code: "AT", alpha3: "AUT", emoji: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", alpha3: "AZE", emoji: "🇦🇿" },
  { name: "The Bahamas", code: "BS", alpha3: "BHS", emoji: "🇧🇸" },
  { name: "Bahrain", code: "BH", alpha3: "BHR", emoji: "🇧🇭" },
  { name: "Bangladesh", code: "BD", alpha3: "BGD", emoji: "🇧🇩" },
  { name: "Barbados", code: "BB", alpha3: "BRB", emoji: "🇧🇧" },
  { name: "Belarus", code: "BY", alpha3: "BLR", emoji: "🇧🇾" },
  { name: "Belgium", code: "BE", alpha3: "BEL", emoji: "🇧🇪" },
  { name: "Belize", code: "BZ", alpha3: "BLZ", emoji: "🇧🇿" },
  { name: "Benin", code: "BJ", alpha3: "BEN", emoji: "🇧🇯" },
  { name: "Bhutan", code: "BT", alpha3: "BTN", emoji: "🇧🇹" },
  { name: "Bolivia", code: "BO", alpha3: "BOL", emoji: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "BA", alpha3: "BIH", emoji: "🇧🇦" },
  { name: "Botswana", code: "BW", alpha3: "BWA", emoji: "🇧🇼" },
  { name: "Brazil", code: "BR", alpha3: "BRA", emoji: "🇧🇷" },
  { name: "Brunei", code: "BN", alpha3: "BRN", emoji: "🇧🇳" },
  { name: "Bulgaria", code: "BG", alpha3: "BGR", emoji: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", alpha3: "BFA", emoji: "🇧🇫" },
  { name: "Burundi", code: "BI", alpha3: "BDI", emoji: "🇧🇮" },
  { name: "Cabo Verde", code: "CV", alpha3: "CPV", emoji: "🇨🇻" },
  { name: "Cambodia", code: "KH", alpha3: "KHM", emoji: "🇰🇭" },
  { name: "Cameroon", code: "CM", alpha3: "CMR", emoji: "🇨🇲" },
  { name: "Canada", code: "CA", alpha3: "CAN", emoji: "🇨🇦" },
  { name: "Central African Republic", code: "CF", alpha3: "CAF", emoji: "🇨🇫" },
  { name: "Chad", code: "TD", alpha3: "TCD", emoji: "🇹🇩" },
  { name: "Chile", code: "CL", alpha3: "CHL", emoji: "🇨🇱" },
  { name: "China", code: "CN", alpha3: "CHN", emoji: "🇨🇳" },
  { name: "Colombia", code: "CO", alpha3: "COL", emoji: "🇨🇴" },
  { name: "Comoros", code: "KM", alpha3: "COM", emoji: "🇰🇲" },
  {
    name: "Congo, Democratic Republic of the",
    code: "CD",
    alpha3: "COD",
    emoji: "🇨🇩",
  },
  { name: "Congo, Republic of the", code: "CG", alpha3: "COG", emoji: "🇨🇬" },
  { name: "Costa Rica", code: "CR", alpha3: "CRI", emoji: "🇨🇷" },
  { name: "Côte d’Ivoire", code: "CI", alpha3: "CIV", emoji: "🇨🇮" },
  { name: "Croatia", code: "HR", alpha3: "HRV", emoji: "🇭🇷" },
  { name: "Cuba", code: "CU", alpha3: "CUB", emoji: "🇨🇺" },
  { name: "Cyprus", code: "CY", alpha3: "CYP", emoji: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", alpha3: "CZE", emoji: "🇨🇿" },
  { name: "Denmark", code: "DK", alpha3: "DNK", emoji: "🇩🇰" },
  { name: "Djibouti", code: "DJ", alpha3: "DJI", emoji: "🇩🇯" },
  { name: "Dominica", code: "DM", alpha3: "DMA", emoji: "🇩🇲" },
  { name: "Dominican Republic", code: "DO", alpha3: "DOM", emoji: "🇩🇴" },
  { name: "East Timor (Timor-Leste)", code: "TL", alpha3: "TLS", emoji: "🇹🇱" },
  { name: "Ecuador", code: "EC", alpha3: "ECU", emoji: "🇪🇨" },
  { name: "Egypt", code: "EG", alpha3: "EGY", emoji: "🇪🇬" },
  { name: "El Salvador", code: "SV", alpha3: "SLV", emoji: "🇸🇻" },
  { name: "Equatorial Guinea", code: "GQ", alpha3: "GNQ", emoji: "🇬🇶" },
  { name: "Eritrea", code: "ER", alpha3: "ERI", emoji: "🇪🇷" },
  { name: "Estonia", code: "EE", alpha3: "EST", emoji: "🇪🇪" },
  { name: "Eswatini", code: "SZ", alpha3: "SWZ", emoji: "🇸🇿" },
  { name: "Ethiopia", code: "ET", alpha3: "ETH", emoji: "🇪🇹" },
  { name: "Fiji", code: "FJ", alpha3: "FJI", emoji: "🇫🇯" },
  { name: "Finland", code: "FI", alpha3: "FIN", emoji: "🇫🇮" },
  { name: "France", code: "FR", alpha3: "FRA", emoji: "🇫🇷" },
  { name: "Gabon", code: "GA", alpha3: "GAB", emoji: "🇬🇦" },
  { name: "The Gambia", code: "GM", alpha3: "GMB", emoji: "🇬🇲" },
  { name: "Georgia", code: "GE", alpha3: "GEO", emoji: "🇬🇪" },
  { name: "Germany", code: "DE", alpha3: "DEU", emoji: "🇩🇪" },
  { name: "Ghana", code: "GH", alpha3: "GHA", emoji: "🇬🇭" },
  { name: "Greece", code: "GR", alpha3: "GRC", emoji: "🇬🇷" },
  { name: "Grenada", code: "GD", alpha3: "GRD", emoji: "🇬🇩" },
  { name: "Guatemala", code: "GT", alpha3: "GTM", emoji: "🇬🇹" },
  { name: "Guinea", code: "GN", alpha3: "GIN", emoji: "🇬🇳" },
  { name: "Guinea-Bissau", code: "GW", alpha3: "GNB", emoji: "🇬🇼" },
  { name: "Guyana", code: "GY", alpha3: "GUY", emoji: "🇬🇾" },
  { name: "Haiti", code: "HT", alpha3: "HTI", emoji: "🇭🇹" },
  { name: "Honduras", code: "HN", alpha3: "HND", emoji: "🇭🇳" },
  { name: "Hungary", code: "HU", alpha3: "HUN", emoji: "🇭🇺" },
  { name: "Iceland", code: "IS", alpha3: "ISL", emoji: "🇮🇸" },
  { name: "India", code: "IN", alpha3: "IND", emoji: "🇮🇳" },
  { name: "Indonesia", code: "ID", alpha3: "IDN", emoji: "🇮🇩" },
  { name: "Iran", code: "IR", alpha3: "IRN", emoji: "🇮🇷" },
  { name: "Iraq", code: "IQ", alpha3: "IRQ", emoji: "🇮🇶" },
  { name: "Ireland", code: "IE", alpha3: "IRL", emoji: "🇮🇪" },
  { name: "Israel", code: "IL", alpha3: "ISR", emoji: "🇮🇱" },
  { name: "Italy", code: "IT", alpha3: "ITA", emoji: "🇮🇹" },
  { name: "Jamaica", code: "JM", alpha3: "JAM", emoji: "🇯🇲" },
  { name: "Japan", code: "JP", alpha3: "JPN", emoji: "🇯🇵" },
  { name: "Jordan", code: "JO", alpha3: "JOR", emoji: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", alpha3: "KAZ", emoji: "🇰🇿" },
  { name: "Kenya", code: "KE", alpha3: "KEN", emoji: "🇰🇪" },
  { name: "Kiribati", code: "KI", alpha3: "KIR", emoji: "🇰🇮" },
  { name: "Korea, North", code: "KP", alpha3: "PRK", emoji: "🇰🇵" },
  { name: "Korea, South", code: "KR", alpha3: "KOR", emoji: "🇰🇷" },
  { name: "Kosovo", code: "XK", alpha3: "XKX", emoji: "🇽🇰" },
  { name: "Kuwait", code: "KW", alpha3: "KWT", emoji: "🇰🇼" },
  { name: "Kyrgyzstan", code: "KG", alpha3: "KGZ", emoji: "🇰🇬" },
  { name: "Laos", code: "LA", alpha3: "LAO", emoji: "🇱🇦" },
  { name: "Latvia", code: "LV", alpha3: "LVA", emoji: "🇱🇻" },
  { name: "Lebanon", code: "LB", alpha3: "LBN", emoji: "🇱🇧" },
  { name: "Lesotho", code: "LS", alpha3: "LSO", emoji: "🇱🇸" },
  { name: "Liberia", code: "LR", alpha3: "LBR", emoji: "🇱🇷" },
  { name: "Libya", code: "LY", alpha3: "LBY", emoji: "🇱🇾" },
  { name: "Liechtenstein", code: "LI", alpha3: "LIE", emoji: "🇱🇮" },
  { name: "Lithuania", code: "LT", alpha3: "LTU", emoji: "🇱🇹" },
  { name: "Luxembourg", code: "LU", alpha3: "LUX", emoji: "🇱🇺" },
  { name: "Madagascar", code: "MG", alpha3: "MDG", emoji: "🇲🇬" },
  { name: "Malawi", code: "MW", alpha3: "MWI", emoji: "🇲🇼" },
  { name: "Malaysia", code: "MY", alpha3: "MYS", emoji: "🇲🇾" },
  { name: "Maldives", code: "MV", alpha3: "MDV", emoji: "🇲🇻" },
  { name: "Mali", code: "ML", alpha3: "MLI", emoji: "🇲🇱" },
  { name: "Malta", code: "MT", alpha3: "MLT", emoji: "🇲🇹" },
  { name: "Marshall Islands", code: "MH", alpha3: "MHL", emoji: "🇲🇭" },
  { name: "Mauritania", code: "MR", alpha3: "MRT", emoji: "🇲🇷" },
  { name: "Mauritius", code: "MU", alpha3: "MUS", emoji: "🇲🇺" },
  { name: "Mexico", code: "MX", alpha3: "MEX", emoji: "🇲🇽" },
  {
    name: "Micronesia, Federated States of",
    code: "FM",
    alpha3: "FSM",
    emoji: "🇫🇲",
  },
  { name: "Moldova", code: "MD", alpha3: "MDA", emoji: "🇲🇩" },
  { name: "Monaco", code: "MC", alpha3: "MCO", emoji: "🇲🇨" },
  { name: "Mongolia", code: "MN", alpha3: "MNG", emoji: "🇲🇳" },
  { name: "Montenegro", code: "ME", alpha3: "MNE", emoji: "🇲🇪" },
  { name: "Morocco", code: "MA", alpha3: "MAR", emoji: "🇲🇦" },
  { name: "Mozambique", code: "MZ", alpha3: "MOZ", emoji: "🇲🇿" },
  { name: "Myanmar (Burma)", code: "MM", alpha3: "MMR", emoji: "🇲🇲" },
  { name: "Namibia", code: "NA", alpha3: "NAM", emoji: "🇳🇦" },
  { name: "Nauru", code: "NR", alpha3: "NRU", emoji: "🇳🇷" },
  { name: "Nepal", code: "NP", alpha3: "NPL", emoji: "🇳🇵" },
  { name: "Netherlands", code: "NL", alpha3: "NLD", emoji: "🇳🇱" },
  { name: "New Zealand", code: "NZ", alpha3: "NZL", emoji: "🇳🇿" },
  { name: "Nicaragua", code: "NI", alpha3: "NIC", emoji: "🇳🇮" },
  { name: "Niger", code: "NE", alpha3: "NER", emoji: "🇳🇪" },
  { name: "Nigeria", code: "NG", alpha3: "NGA", emoji: "🇳🇬" },
  { name: "North Macedonia", code: "MK", alpha3: "MKD", emoji: "🇲🇰" },
  { name: "Norway", code: "NO", alpha3: "NOR", emoji: "🇳🇴" },
  { name: "Oman", code: "OM", alpha3: "OMN", emoji: "🇴🇲" },
  { name: "Pakistan", code: "PK", alpha3: "PAK", emoji: "🇵🇰" },
  { name: "Palau", code: "PW", alpha3: "PLW", emoji: "🇵🇼" },
  { name: "Panama", code: "PA", alpha3: "PAN", emoji: "🇵🇦" },
  { name: "Papua New Guinea", code: "PG", alpha3: "PNG", emoji: "🇵🇬" },
  { name: "Paraguay", code: "PY", alpha3: "PRY", emoji: "🇵🇾" },
  { name: "Peru", code: "PE", alpha3: "PER", emoji: "🇵🇪" },
  { name: "Philippines", code: "PH", alpha3: "PHL", emoji: "🇵🇭" },
  { name: "Poland", code: "PL", alpha3: "POL", emoji: "🇵🇱" },
  { name: "Portugal", code: "PT", alpha3: "PRT", emoji: "🇵🇹" },
  { name: "Qatar", code: "QA", alpha3: "QAT", emoji: "🇶🇦" },
  { name: "Romania", code: "RO", alpha3: "ROU", emoji: "🇷🇴" },
  { name: "Russia", code: "RU", alpha3: "RUS", emoji: "🇷🇺" },
  { name: "Rwanda", code: "RW", alpha3: "RWA", emoji: "🇷🇼" },
  { name: "Saint Kitts and Nevis", code: "KN", alpha3: "KNA", emoji: "🇰🇳" },
  { name: "Saint Lucia", code: "LC", alpha3: "LCA", emoji: "🇱🇨" },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    alpha3: "VCT",
    emoji: "🇻🇨",
  },
  { name: "Samoa", code: "WS", alpha3: "WSM", emoji: "🇼🇸" },
  { name: "San Marino", code: "SM", alpha3: "SMR", emoji: "🇸🇲" },
  { name: "Sao Tome and Principe", code: "ST", alpha3: "STP", emoji: "🇸🇹" },
  { name: "Saudi Arabia", code: "SA", alpha3: "SAU", emoji: "🇸🇦" },
  { name: "Senegal", code: "SN", alpha3: "SEN", emoji: "🇸🇳" },
  { name: "Serbia", code: "RS", alpha3: "SRB", emoji: "🇷🇸" },
  { name: "Seychelles", code: "SC", alpha3: "SYC", emoji: "🇸🇨" },
  { name: "Sierra Leone", code: "SL", alpha3: "SLE", emoji: "🇸🇱" },
  { name: "Singapore", code: "SG", alpha3: "SGP", emoji: "🇸🇬" },
  { name: "Slovakia", code: "SK", alpha3: "SVK", emoji: "🇸🇰" },
  { name: "Slovenia", code: "SI", alpha3: "SVN", emoji: "🇸🇮" },
  { name: "Solomon Islands", code: "SB", alpha3: "SLB", emoji: "🇸🇧" },
  { name: "Somalia", code: "SO", alpha3: "SOM", emoji: "🇸🇴" },
  { name: "South Africa", code: "ZA", alpha3: "ZAF", emoji: "🇿🇦" },
  { name: "Spain", code: "ES", alpha3: "ESP", emoji: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", alpha3: "LKA", emoji: "🇱🇰" },
  { name: "Sudan", code: "SD", alpha3: "SDN", emoji: "🇸🇩" },
  { name: "Sudan, South", code: "SS", alpha3: "SSD", emoji: "🇸🇸" },
  { name: "Suriname", code: "SR", alpha3: "SUR", emoji: "🇸🇷" },
  { name: "Sweden", code: "SE", alpha3: "SWE", emoji: "🇸🇪" },
  { name: "Switzerland", code: "CH", alpha3: "CHE", emoji: "🇨🇭" },
  { name: "Syria", code: "SY", alpha3: "SYR", emoji: "🇸🇾" },
  { name: "Taiwan", code: "TW", alpha3: "TWN", emoji: "🇹🇼" },
  { name: "Tajikistan", code: "TJ", alpha3: "TJK", emoji: "🇹🇯" },
  { name: "Tanzania", code: "TZ", alpha3: "TZA", emoji: "🇹🇿" },
  { name: "Thailand", code: "TH", alpha3: "THA", emoji: "🇹🇭" },
  { name: "Togo", code: "TG", alpha3: "TGO", emoji: "🇹🇬" },
  { name: "Tonga", code: "TO", alpha3: "TON", emoji: "🇹🇴" },
  { name: "Trinidad and Tobago", code: "TT", alpha3: "TTO", emoji: "🇹🇹" },
  { name: "Tunisia", code: "TN", alpha3: "TUN", emoji: "🇹🇳" },
  { name: "Turkey", code: "TR", alpha3: "TUR", emoji: "🇹🇷" },
  { name: "Turkmenistan", code: "TM", alpha3: "TKM", emoji: "🇹🇲" },
  { name: "Tuvalu", code: "TV", alpha3: "TUV", emoji: "🇹🇻" },
  { name: "Uganda", code: "UG", alpha3: "UGA", emoji: "🇺🇬" },
  { name: "Ukraine", code: "UA", alpha3: "UKR", emoji: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", alpha3: "ARE", emoji: "🇦🇪" },
  { name: "United Kingdom", code: "GB", alpha3: "GBR", emoji: "🇬🇧" },
  { name: "United States", code: "US", alpha3: "USA", emoji: "🇺🇸" },
  { name: "Uruguay", code: "UY", alpha3: "URY", emoji: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", alpha3: "UZB", emoji: "🇺🇿" },
  { name: "Vanuatu", code: "VU", alpha3: "VUT", emoji: "🇻🇺" },
  { name: "Vatican City", code: "VA", alpha3: "VAT", emoji: "🇻🇦" },
  { name: "Venezuela", code: "VE", alpha3: "VEN", emoji: "🇻🇪" },
  { name: "Vietnam", code: "VN", alpha3: "VNM", emoji: "🇻🇳" },
  { name: "Yemen", code: "YE", alpha3: "YEM", emoji: "🇾🇪" },
  { name: "Zambia", code: "ZM", alpha3: "ZMB", emoji: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", alpha3: "ZWE", emoji: "🇿🇼" },
];
